import {beforeEach,describe,expect,it,vi} from 'vitest';
const mocks=vi.hoisted(()=>({requireRole:vi.fn(),flag:vi.fn(),db:{student:{findUnique:vi.fn()},dailyLog:{findMany:vi.fn(),findFirst:vi.fn(),create:vi.fn(),count:vi.fn(),updateMany:vi.fn()},reviewQueueItem:{count:vi.fn(),findFirst:vi.fn()}}}));
vi.mock('@/lib/auth',()=>({requireRole:mocks.requireRole}));
vi.mock('@/lib/db',()=>({db:mocks.db}));
vi.mock('@/lib/systemConfig',()=>({isFeatureEnabled:mocks.flag}));
import {GET,POST} from './route';
const req=(body:unknown)=>new Request('http://localhost/api/student/micro-learning',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
beforeEach(()=>{vi.resetAllMocks();mocks.requireRole.mockResolvedValue({student:{id:'s1',studentCode:'211'}});mocks.flag.mockResolvedValue(true);mocks.db.student.findUnique.mockResolvedValue({id:'s1',gradeLevel:'YDS'});mocks.db.dailyLog.count.mockResolvedValue(0);mocks.db.dailyLog.create.mockResolvedValue({id:'session',createdAt:new Date()});mocks.db.dailyLog.findMany.mockResolvedValue([]);mocks.db.reviewQueueItem.count.mockResolvedValue(0)});
describe('micro learning API',()=>{
  it('rejects unavailable categories on the server',async()=>{const r=await POST(req({action:'start',kind:'LIT_MATCH_3'}));expect(r.status).toBe(400);expect(mocks.db.dailyLog.create).not.toHaveBeenCalled()});
  it('starts a new student without learning history and hides the answer key',async()=>{const r=await POST(req({action:'start',kind:'WORDS_5'}));const j=await r.json();expect(r.status).toBe(200);expect(j.pack.items).toHaveLength(5);expect(j.pack.items[0]).not.toHaveProperty('answer');expect(mocks.db.dailyLog.create.mock.calls[0][0].data.payload).not.toHaveProperty('items')});
  it('enforces ownership on submitted sessions',async()=>{mocks.db.dailyLog.findFirst.mockResolvedValue(null);const r=await POST(req({action:'submit',sessionId:'foreign',answers:{'0':'kitap'}}));expect(r.status).toBe(404);expect(mocks.db.dailyLog.findFirst).toHaveBeenCalledWith({where:{id:'foreign',studentId:'s1'}});expect(mocks.db.dailyLog.updateMany).not.toHaveBeenCalled()});
  it('honors the feature switch before database work',async()=>{mocks.flag.mockResolvedValue(false);expect((await GET()).status).toBe(403);expect(mocks.db.student.findUnique).not.toHaveBeenCalled()});
  it('makes retries idempotent after a successful completion',async()=>{const result={correct:3,total:5};mocks.db.dailyLog.findFirst.mockResolvedValue({payload:{type:'MICRO_RESULT',result}});const r=await POST(req({action:'submit',sessionId:'session',answers:{'0':'kitap'}}));expect(await r.json()).toEqual({ok:true,result});expect(mocks.db.dailyLog.updateMany).not.toHaveBeenCalled()});
  it('grades on the server and conditionally saves only an unfinished session',async()=>{mocks.db.dailyLog.findFirst.mockResolvedValue({id:'session',createdAt:new Date(),payload:{type:'MICRO_STARTED',version:1,kind:'PROBLEM_3',level:'primary',variant:0}});mocks.db.dailyLog.updateMany.mockResolvedValue({count:1});const r=await POST(req({action:'submit',sessionId:'session',answers:{'0':'4'},score:999}));expect((await r.json()).result).toMatchObject({correct:1,blank:2,wrong:0});expect(mocks.db.dailyLog.updateMany.mock.calls[0][0].where).toMatchObject({studentId:'s1',payload:{path:['type'],equals:'MICRO_STARTED'}})});
  it('rejects a concurrent duplicate completion',async()=>{mocks.db.dailyLog.findFirst.mockResolvedValue({id:'session',createdAt:new Date(),payload:{type:'MICRO_STARTED',version:1,kind:'PROBLEM_3',level:'primary',variant:0}});mocks.db.dailyLog.updateMany.mockResolvedValue({count:0});expect((await POST(req({action:'submit',sessionId:'session',answers:{'0':'4'}}))).status).toBe(409)});
  it('does not create an invented wrong question when the review queue is empty',async()=>{mocks.db.reviewQueueItem.findFirst.mockResolvedValue(null);expect((await POST(req({action:'start',kind:'WRONG_1'}))).status).toBe(409);expect(mocks.db.dailyLog.create).not.toHaveBeenCalled()});
});
