export type Audience='STUDENT'|'COACH';
export type KeksPlan={id:string;name:string;audience:Audience;level:string;price:number|null;capacity?:number;features:string[]};

export const STUDENT_PLANS:KeksPlan[]=[
{id:'student-primary-12',name:'KEKS Başlangıç',audience:'STUDENT',level:'İlkokul 1–2',price:2000,features:['Eğitim düzeyine uygun Eğilim Taraması','Bugünün Planı ve kısa günlük görevler','Okuma, sorumluluk ve çalışma alışkanlığı takibi','Yaşa uygun mikro öğrenme ve basitleştirilmiş tekrar','Görev tamamlama ve süreklilik takibi','Öğrenci gelişim ekranı ve veli paneli','Aylık KEKS Gelişim Raporu']},
{id:'student-primary-34',name:'KEKS Temel',audience:'STUDENT',level:'İlkokul 3–4',price:2250,features:['KEKS Başlangıç özellikleri','Kişisel haftalık çalışma planı','Soru, doğru, yanlış ve boş kayıtları','Yanlış soru arşivi ve kaynak takibi','Yaşa uyarlanmış 0–1–3–7–14–28 tekrar sistemi','Odak çalışma araçları','Aylık gelişim raporu ve veli takibi']},
{id:'student-middle-56',name:'KEKS Gelişim',audience:'STUDENT',level:'Ortaokul 5–6',price:2500,features:['Eğilim Taraması ve kişisel çalışma stratejisi','Bugünün Planı ve günlük görev yönetimi','Soru/doğru/yanlış/boş performans takibi','Kişisel yanlış soru bankası','Kaynak-konu-sayfa-soru takibi','0–1–3–7–14–28 tekrar ve mikro öğrenme','Bilgi hâkimiyeti, odak/süre takibi ve aylık rapor']},
{id:'student-lgs-prep',name:'KEKS LGS Hazırlık',audience:'STUDENT',level:'7. Sınıf',price:3000,features:['KEKS Gelişim özellikleri','MEB ders-konu-alt konu-kazanım-soru tipi haritası','Yeni nesil soru ve konu hâkimiyeti','Deneme kayıtları ve net trendleri','Yanlış nedenleri sınıflandırması','Dinamik planlama ve geciken tekrarların dağıtılması','Gerçek çalışma kapasitesi analizi ve MİZA']},
{id:'student-lgs-360',name:'KEKS LGS 360',audience:'STUDENT',level:'8. Sınıf / LGS',price:4500,features:['Eğilim Taraması ve kişisel çalışma stratejisi','MEB/LGS kazanım haritası ve dinamik Bugünün Planı','LGS deneme/net ve kazanım analizi','Yeni nesil soru performansı ve yanlış nedenleri','Kişisel soru bankası, haftalık yanlışlar ve aylık karma tekrar','Kaynak verimliliği, bilgi hâkimiyeti ve kişisel tekrar motoru','MİZA, Morning Brief, görüşme hazırlığı ve koç aksiyonları','Veli paneli ve kapsamlı aylık KEKS Gelişim Raporu']},
{id:'student-high-910',name:'KEKS Lise Gelişim',audience:'STUDENT',level:'Lise 9–10',price:3000,features:['Bugünün Planı ve kişisel haftalık program','Okul dersleri konu/kazanım takibi','TYT altyapısı, paragraf ve problem rutinleri','Kaynak takibi ve yanlış soru bankası','Bilgi hâkimiyeti ve tekrar motoru','Mikro öğrenme ve çalışma kapasitesi analizi','MİZA ve aylık gelişim raporu']},
{id:'student-yks-prep',name:'KEKS YKS Hazırlık',audience:'STUDENT',level:'Lise 11',price:3500,features:['Lise Gelişim özellikleri','TYT + 11. sınıf/AYT dengeli çalışma','Hedef üniversite/bölüm ve hedef-net farkı','TYT net trendleri ve deneme analizi','Ders-konu-kazanım ve kaynak yönetimi','Yanlış nedenleri, kişisel yanlışlar ve bilgi hâkimiyeti','Dinamik plan, kişisel tekrar algoritması ve MİZA']},
{id:'student-yks-360',name:'KEKS YKS 360',audience:'STUDENT',level:'12. Sınıf / YKS',price:5000,features:['Eğilim Taraması ve kişisel çalışma stratejisi','Hedef üniversite/bölüm ve hedef-net farkı','Dinamik TYT/AYT Bugünün Planı ve kapasite analizi','Deneme/net, konu/kazanım ve yanlış nedenleri analizi','Kişisel soru bankası, kaynak verimliliği ve bilgi hâkimiyeti','Kişisel unutma eğrisi, otomatik tekrar ve mikro öğrenme','MİZA, Morning Brief, koç aksiyonları ve görüşme hazırlığı','Veli paneli ve aylık KEKS Gelişim Raporu']},
{id:'student-mezun-360',name:'KEKS Mezun 360',audience:'STUDENT',level:'YKS Mezun',price:5000,features:['KEKS YKS 360 özellikleri','Mezun kapasitesine göre yoğun çalışma blokları','Yoğun TYT/AYT deneme döngüsü','Konu kapatma takvimi','Planlanan-gerçekleşen süre analizi','Sürdürülebilirlik ve verimli saat analizi','Geciken görevlerin kapasiteye göre yeniden dağıtılması']},
{id:'student-kamu',name:'KEKS Kamu',audience:'STUDENT',level:'KPSS / EKPSS',price:3500,features:['Sınav düzeyine uygun kişisel plan','Genel Yetenek/Genel Kültür konu haritası','Soru, deneme ve net trendleri','Kaynak yönetimi ve yanlış soru bankası','Bilgi hâkimiyeti, aktif hatırlama ve tekrar','Mikro öğrenme ve dinamik program','MİZA ve aylık gelişim raporu']},
{id:'student-dgs',name:'KEKS DGS',audience:'STUDENT',level:'DGS',price:3500,features:['Kişisel günlük/haftalık plan','Sayısal-sözel soru türü performansı','Hız, doğruluk ve soru başına süre','Problem/paragraf rutinleri ve deneme analizi','Yanlış nedenleri ve kişisel soru bankası','Dinamik plan, tekrar ve mikro öğrenme','MİZA ve aylık gelişim raporu']},
{id:'student-ales',name:'KEKS ALES',audience:'STUDENT',level:'ALES',price:3000,features:['Sayısal/sözel çalışma planı','Soru türü bazlı hız ve doğruluk','Süre yönetimi ve deneme performansı','Problem/paragraf rutinleri','Yanlış soru bankası ve yanlış nedenleri','Dinamik tekrar ve mikro öğrenme','MİZA destekli gelişim takibi']},
{id:'student-language',name:'KEKS Dil',audience:'STUDENT',level:'YDS / YÖKDİL',price:4000,features:['Kelime mikro öğrenmesi ve kişisel kelime tekrar sistemi','0–1–3–7–14–28 aralıklı tekrar','Okuma ve soru türü performansı','Yanlış soru bankası ve kaynak takibi','Deneme/net ve süre analizi','Bilgi hâkimiyeti ve dinamik plan','MİZA ve aylık gelişim raporu']},
{id:'student-ags-language',name:'KEKS AGS Dil',audience:'STUDENT',level:'AGS / YDS',price:4500,features:['AGS ve YDS performansının ayrı takibi','AGS konu haritası ve dil/kelime sistemi','Kişisel günlük plan ve dinamik program','Deneme/net, süre ve yanlış nedenleri','Kaynak, bilgi hâkimiyeti ve tekrar motoru','MİZA ve koç aksiyon önerileri','Aylık kapsamlı gelişim raporu']},
{id:'student-teacher-360',name:'KEKS Öğretmen 360',audience:'STUDENT',level:'AGS / ÖABT',price:4500,features:['AGS ve seçilen ÖABT alanının ayrı takibi','Alana özgü ders-konu-alt konu-kazanım haritası','Bugünün Planı ve dinamik program','Deneme/net, kaynak ve yanlış soru analizi','Bilgi hâkimiyeti ve kişisel tekrar algoritması','MİZA, Morning Brief ve koç aksiyonları','Otomatik görüşme hazırlığı ve aylık kapsamlı rapor']}
];
export const COACH_PLANS:KeksPlan[]=[
{id:'coach-start',name:'KEKS Koç Start',audience:'COACH',level:'10 aktif öğrenci',capacity:10,price:2000,features:['Öğrenci profili ve eşleştirme','Program ve görev yönetimi','Soru, deneme ve performans takibi','Tekrar ve bilgi hâkimiyeti','Kaynak ve yanlış soru bankası','Görüşme notları ve temel raporlar']},
{id:'coach-pro',name:'KEKS Koç Pro',audience:'COACH',level:'30 aktif öğrenci',capacity:30,price:3500,features:['Koç Start özellikleri','Eğilim Taraması sonuçları','MİZA koç desteği','Morning Brief','Otomatik görüşme hazırlığı','Açıklanabilir koç aksiyon önerileri','Gelişmiş haftalık/aylık raporlar']},
{id:'coach-expert',name:'KEKS Koç Expert',audience:'COACH',level:'75 aktif öğrenci',capacity:75,price:6000,features:['Koç Pro özellikleri','Toplu öğrenci yönetimi ve segmentasyon','Gelişmiş performans analitiği','Koç aksiyon etkisi','Geciken görev/tekrarların toplu takibi','Gelişmiş raporlama ve otomasyon']},
{id:'coach-business',name:'KEKS Koç Business',audience:'COACH',level:'150 aktif öğrenci',capacity:150,price:9000,features:['Koç Expert özellikleri','Yüksek hacimli öğrenci yönetimi','Ekip ve operasyon görünümü','Koç kalite metrikleri','Gelişmiş otomasyon ve kapsamlı raporlama','Öncelikli operasyon desteği']},
{id:'coach-enterprise',name:'KEKS Kurum',audience:'COACH',level:'150+ / çoklu koç',price:null,features:['Çoklu koç ve yönetici yapısı','Öğrenci-koç dağıtımı','Rol ve yetki yönetimi','Kurum geneli performans analitiği','Koç kalite sistemi','Toplu yönetim ve kurumsal raporlama']}
];
export const ALL_PLANS=[...STUDENT_PLANS,...COACH_PLANS];
